# Generated by Django 5.2.6 on 2025-09-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="provider",
            field=models.CharField(
                blank=True,
                help_text="Social login provider (google, kakao)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="provider_id",
            field=models.CharField(
                blank=True, help_text="Provider user ID", max_length=100, null=True
            ),
        ),
    ]
