# Generated by Django 5.2.6 on 2025-09-15 04:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIServiceConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_name", models.CharField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("configuration", models.JSONField(default=dict)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "easystyle_ai_service_configurations",
            },
        ),
        migrations.CreateModel(
            name="AIStyleRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("style_prompt", models.TextField()),
                (
                    "user_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="ai_requests/user_images/"
                    ),
                ),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_style_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "easystyle_ai_style_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIProductRecommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("recommendation_prompt", models.TextField()),
                ("recommended_products", models.JSONField(default=list)),
                ("recommendation_reason", models.TextField()),
                ("user_style_analysis", models.JSONField(default=dict)),
                ("color_palette", models.JSONField(default=list)),
                ("style_categories", models.JSONField(default=list)),
                (
                    "user_rating",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        null=True,
                    ),
                ),
                ("user_feedback", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_product_recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "style_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_recommendations",
                        to="ai_services.aistylerequest",
                    ),
                ),
            ],
            options={
                "db_table": "easystyle_ai_product_recommendations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIStyleResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "generated_image",
                    models.ImageField(upload_to="ai_responses/generated_images/"),
                ),
                ("ai_description", models.TextField()),
                ("confidence_score", models.FloatField(default=0.0)),
                ("processing_time", models.FloatField(blank=True, null=True)),
                ("algorithm_version", models.CharField(default="1.0", max_length=50)),
                (
                    "user_rating",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        null=True,
                    ),
                ),
                ("user_feedback", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="response",
                        to="ai_services.aistylerequest",
                    ),
                ),
            ],
            options={
                "db_table": "easystyle_ai_style_responses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIServiceLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("debug", "Debug"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                ("service_name", models.CharField(max_length=100)),
                ("message", models.TextField()),
                ("details", models.JSONField(blank=True, default=dict)),
                ("request_id", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "easystyle_ai_service_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["service_name", "level"],
                        name="easystyle_a_service_8f8bd0_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="easystyle_a_created_635076_idx"
                    ),
                ],
            },
        ),
    ]
